/// Wrapper around the protobuf code generated for EncryptedMessageProto.
/// Uses code generated by protoc in lib/services/generated/
///
/// Protobuf encoding is much more compact than JSON:
/// - JSON: {"s":"userId123","t":1707408000000,"c":false,"y":0,"content":"Hello"} = ~70 bytes
/// - Protobuf: ~30 bytes (about 50-60% reduction)
///
/// Format: The complete protobuf message is encrypted with XOR (One-Time Pad)
library;

import 'dart:typed_data';

import 'package:fixnum/fixnum.dart';

import '../models/firestore/fs_message.dart';
import '../generated/message.pb.dart' as proto;

/// Complete message encoded in Protobuf, ready to be encrypted.
/// Contains metadata AND message content.
///
/// Wrapper around the code generated by protoc to maintain
/// a compatible API with the rest of the code.
class EncryptedMessageProto {
  /// Sender ID
  final String senderId;

  /// Creation timestamp (milliseconds since epoch)
  final int createdAtMs;

  /// Indicates if content was compressed before encryption
  final bool isCompressed;

  /// Content type (0=text, 1=image, 2=file)
  final MessageContentType contentType;

  /// File name (optional, for files and images)
  final String? fileName;

  /// MIME type of the file (optional)
  final String? mimeType;

  /// Message content (UTF-8 encoded text or raw binary)
  final Uint8List content;

  EncryptedMessageProto({
    required this.senderId,
    required this.createdAtMs,
    required this.isCompressed,
    required this.contentType,
    this.fileName,
    this.mimeType,
    required this.content,
  });

  DateTime get createdAt => DateTime.fromMillisecondsSinceEpoch(createdAtMs);

  /// Encodes to binary protobuf format using generated code.
  Uint8List toBytes() {
    final message = proto.EncryptedMessageProto(
      senderId: senderId,
      createdAtMs: Int64(createdAtMs),
      isCompressed: isCompressed,
      contentType: contentType.index,
      fileName: fileName,
      mimeType: mimeType,
      content: content,
    );

    return Uint8List.fromList(message.writeToBuffer());
  }

  /// Decodes from binary protobuf format using generated code.
  factory EncryptedMessageProto.fromBytes(Uint8List bytes) {
    final message = proto.EncryptedMessageProto.fromBuffer(bytes);

    return EncryptedMessageProto(
      senderId: message.senderId,
      createdAtMs: message.createdAtMs.toInt(),
      isCompressed: message.isCompressed,
      contentType: MessageContentType.values[
        message.contentType.clamp(0, MessageContentType.values.length - 1)
      ],
      fileName: message.hasFileName() ? message.fileName : null,
      mimeType: message.hasMimeType() ? message.mimeType : null,
      content: Uint8List.fromList(message.content),
    );
  }

  @override
  String toString() {
    return 'EncryptedMessageProto(sender=$senderId, type=${contentType.name}, '
           'content=${content.length} bytes${isCompressed ? ', compressed' : ''})';
  }
}
